import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";
import Container from "@mui/material/Container";
import {ToastContainer} from "react-toastify";
import 'react-toastify/dist/ReactToastify.css'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Personal book manager",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <ToastContainer position='top-right' />
      <Header />
      <Container maxWidth="lg" style={{paddingTop: "20px"}}>
        {children}
      </Container>
      </body>
    </html>
  );
}
